### ISSUE TITLE
buildozer.spec file?!

### ISSUE THREAD

**Issue by ignamendi21** [IbrahimAlsaadany/kivy-mobile-app-arduino-bluetooth#1]
Hei! Can you upload the buildozer.spec file please??????? :  )

**Comment by IbrahimAlsaadany** [comment]
> Hei! Can you upload the buildozer.spec file please??????? : )
Sure

**Comment by IbrahimAlsaadany** [comment]
> Hei! Can you upload the buildozer.spec file please??????? : ) <
Sure

**Comment by IbrahimElsaadany** [comment]
> Hei! Can you upload the buildozer.spec file please??????? : )

Sure
